/*
 * This file is generated by `npm run album:upload -- <folder> --expected 45`.
 * Keep an empty, typed manifest in git so a fresh checkout can type-check
 * before the first ImageKit upload. The runtime resolver supplies local demo
 * images whenever this manifest (or ImageKit itself) is empty.
 */

import type { AlbumImage } from "./wedding";

export interface GeneratedGalleryManifest {
  version: 1;
  generatedAt: string | null;
  folder: string;
  expectedCount: number;
  images: AlbumImage[];
}

export const GENERATED_ALBUM: AlbumImage[] = [];

export const GALLERY_MANIFEST: GeneratedGalleryManifest = {
  version: 1,
  generatedAt: null,
  folder: "/wedding/thuong-huy/",
  expectedCount: 45,
  images: GENERATED_ALBUM,
};

/** Lower-case aliases are convenient for data-oriented imports. */
export const generatedAlbum = GENERATED_ALBUM;
export const galleryGenerated = GALLERY_MANIFEST;

export default GALLERY_MANIFEST;

